# Site settings
title: TITLE
description: DESCRIOPTION
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sergej Schefer
user_description: user_description
user_title: Game Developer
email: sergej.schefer@web.de
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
