# Site settings
title: Sergej Schefer
description: Game Developer
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sergej Schefer
user_title: Game Developer
email: sergej.schefer@web.de

exclude: ['package.json', 'src' , 'node_modules']
